cloud:
  aws:
    endpoint-url: http://localhost:4566/
    region:
      static: <REGION_NAME>
    credentials:
      access-key: <DUMMY_ACCESS_KEY>
      secret-key: <DUMMY_SECRET_ACCESS_KEY>
    kinesis:
      stream-name: <SAMPLE_STREAM_NAME>